---
- name: Create folder to store Appimage files
  file:
    path: "/home/{{ home_user }}/Applications"
    state: directory
  become_user: "{{ home_user }}"
  become: false

- name: Download appimaged AppImage file
  get_url:
      dest: "/home/{{ home_user }}/Applications/appimaged-715.Appimage"
      url: https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-{{ appimaged_version }}-x86_64.AppImage
  become_user: "{{ home_user }}"
  become: false

- name: Download AppImage Updater
  get_url:
      dest: "/home/{{ home_user }}/Applications/AppImageUpdater-2.0.0.Appimage"
      url: https://github.com/AppImage/AppImageUpdate/releases/download/2.0.0-alpha-1-20220124/AppImageUpdate-x86_64.AppImage
  become_user: "{{ home_user }}"
  become: false

- name: Download Nextcloud AppImage file
  get_url:
      dest: "/home/{{ home_user }}/Applications/Nextcloud-{{ nextcloud_version }}.Appimage"
      url: "https://github.com/nextcloud/desktop/releases/download/v{{ nextcloud_version }}/Nextcloud-{{ nextcloud_version }}-x86_64.AppImage"
  become_user: "{{ home_user }}"
  become: false