---
- name: Create folder to store Appimage files
  file:
    path: "/home/{{ home_user }}/Applications"
    state: directory
  become_user: "{{ home_user }}"
  become: false
        
- name: Download Obsidian .AppImage file
  get_url:
      dest: "/home/{{ home_user }}/Applications/Obsidian-0.13.14.Appimage"
      url: https://github.com/obsidianmd/obsidian-releases/releases/download/v0.13.14/Obsidian-0.13.14.AppImage
  become_user: "{{ home_user }}"
  become: false