---
- name: Install .deb packages
  apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    - https://github.com/xournalpp/xournalpp/releases/download/v{{ xournalpp_version }}/xournalpp-{{ xournalpp_version }}-Ubuntu-focal-x86_64.deb      
    - https://discord.com/api/download?platform=linux&format=deb
    - https://github.com/RustScan/RustScan/releases/download/{{ rustscan_version }}/rustscan_{{ rustscan_version }}_amd64.deb
    
- name: Install required applications
  apt:
    update_cache: true
    name:
    - python3
    - python3-pip
    - flatpak
    - vlc
    - git
    - make
    - whois
    - vim
    - htop
    - xz-utils
    - neofetch
    - appimagelauncher
    - virtualbox
    - vagrant
    - discord
    - brave-browser
    - telegram-desktop
    - krita
    - appimagelauncher
    - rustscan
    state: present